### ISSUE TITLE
package ‘unixtools’ is not available for this version of R

### ISSUE THREAD

**Issue by bitbacchus** [s-u/unixtools#4]
Hi,

unixtools seems to be not available on CRAN for R 4.0.x

```
> install.packages("unixtools")
Installing package into ‘/home/bacchus/R/x86_64-pc-linux-gnu-library/4.1’
(as ‘lib’ is unspecified)
Warning in install.packages :
  package ‘unixtools’ is not available for this version of R

A version of this package for your version of R might be available elsewhere,
see the ideas at
https://cran.r-project.org/doc/manuals/r-patched/R-admin.html#Installing-packages
``` 

Best,

Sebastian

**Comment by whositwhatnow** [comment]
any update on this?

**Comment by s-u** [comment]
```r
install.packages("unixtools",repos="https://rforge.net")
```

**Comment by whositwhatnow** [comment]
> install.packages("unixtools",repos="https://rforge.net")
Warning: unable to access index for repository https://rforge.net/src/contrib:
  cannot open URL 'https://rforge.net/src/contrib/PACKAGES'
Warning message:
package ‘unixtools’ is not available for this version of R

A version of this package for your version of R might be available elsewhere,
see the ideas at
https://cran.r-project.org/doc/manuals/r-patched/R-admin.html#Installing-package                                                                                    s

**Comment by whositwhatnow** [comment]
install.packages("unixtools",,'http://rforge.net/',type='source')
